### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by justechn** [rochejul/sequelize-mocking#3]
I get this warning when using this library

Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (C:\Users\rmclaughlin\Documents\projects\memories-lambda-fullobituary\node_modules\sequelize-mocking\node_modules\sequelize\node_modules\moment\moment.js:850:105)
    at configFromString (C:\Users\rmclaughlin\Documents\projects\memories-lambda-fullobituary\node_modules\sequelize-mocking\node_modules\sequelize\node_modules\moment\moment.js:970:32)
    at configFromInput (C:\Users\rmclaughlin\Documents\projects\memories-lambda-fullobituary\node_modules\sequelize-mocking\node_modules\sequelize\node_modules\moment\moment.js:1473:13)
    at prepareConfig (C:\Users\rmclaughlin\Documents\projects\memories-lambda-fullobituary\node_modules\sequelize-mocking\node_modules\sequelize\node_modules\moment\moment.js:1456:13)

I am using node ver 4.5.0

**Comment by rochejul** [comment]
Hi

This is an issue on Sequelize side. You have two issues to reference it:
- https://github.com/sequelize/sequelize/issues/6483
- https://github.com/sequelize/sequelize/issues/4954

Due to this line of code: https://github.com/sequelize/sequelize/blob/v3.24.1/lib/data-types.js#L473

It seems to  "resolve it", you have to specify ISO date (see https://github.com/sequelize/sequelize/issues/4954), however, there is a pull request to fix it: https://github.com/sequelize/sequelize/pull/6206

I will update the dependency version when the pull request is integrated.

Many thanks for your feedback

Cheers

**Comment by justechn** [comment]
Thanks for the quick response
