### ISSUE TITLE
Sequelize.fn not working

### ISSUE THREAD

**Issue by cameronprattedwards** [rochejul/sequelize-mocking#7]
Given a model that looks like this:

```javascript
export default function(sequelize, DataTypes) {
  var User = sequelize.define('User', {
    email: {type: DataTypes.STRING, unique: true},
    password: DataTypes.STRING,
    salt: DataTypes.STRING,
  }, {
    timestamps: false,
    tableName: 'users',
  });

  return User;
}
```

And a query that looks like this:

```javascript
import {User, Sequelize} from 'models';

const USER_NOT_FOUND = 'api/server/login/USER_NOT_FOUND';

function login(email, password) {
  return User.findOne({
    where: {
      email,
      password: Sequelize.fn('sha1', Sequelize.fn('concat', password, Sequelize.col('salt'))),
    },
  });
}

export {login, USER_NOT_FOUND};
```

And a test that looks like this:

```javascript
  it('returns a user with the correct username and password', done => {
    login('testuser@gmail.com', 'password')
      .then(user => expect(user.id).toBe(1))
      .catch(e => console.log(e))
      .finally(done);
  });
```

I get an error like this:

```
      Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: object Object
          at Query.Object.<anonymous>.Query.formatError (/Users/cameronedwards/Repos/cleanstreamit/node_modules/sequelize-mocking/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
          at afterExecute (/Users/cameronedwards/Repos/cleanstreamit/node_modules/sequelize-mocking/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
          at replacement (/Users/cameronedwards/Repos/cleanstreamit/node_modules/sequelize-mocking/node_modules/sqlite3/lib/trace.js:20:31)
          at Statement.errBack (/Users/cameronedwards/Repos/cleanstreamit/node_modules/sequelize-mocking/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

Logged out, the whole error looks like this:

```
      Error {
        name: 'SequelizeDatabaseError',
        message: 'SQLITE_ERROR: no such column: object Object',
        parent: 
         { Error: SQLITE_ERROR: no such column: object Object
             at Error (native)
           errno: 1,
           code: 'SQLITE_ERROR',
           sql: 'SELECT `id`, `email`, `password`, `salt` FROM `users` AS `User` WHERE `User`.`email` = \'testuser@gmail.com\' AND [object Object] LIMIT 1;' },
        original: 
         { Error: SQLITE_ERROR: no such column: object Object
             at Error (native)
           errno: 1,
           code: 'SQLITE_ERROR',
           sql: 'SELECT `id`, `email`, `password`, `salt` FROM `users` AS `User` WHERE `User`.`email` = \'testuser@gmail.com\' AND [object Object] LIMIT 1;' },
        sql: 'SELECT `id`, `email`, `password`, `salt` FROM `users` AS `User` WHERE `User`.`email` = \'testuser@gmail.com\' AND [object Object] LIMIT 1;' }
```

**Comment by rochejul** [comment]
I have got 
![image](https://user-images.githubusercontent.com/244999/33662116-f94f4a6e-da8a-11e7-8e52-cd9a7b8f5479.png) 

That probably means the sha1 method does not exist 

Regards
